### PR TITLE
documented research case

### PR DESCRIPTION
**Pull request by paolo-demagistris-polito**
@EminSuleyman check /Scope/research-case.md

### CODE REVIEW

**Review by EminSuleyman — COMMENTED** [review]
review is done

**Comment by paolo-demagistris-polito** [comment]
> review is done

and?

**Comment by EminSuleyman** [comment]
as a conclusion, general structure understood, just need to clarify specific tasks for the backend api, and if frontend is ready I would like to see it too.

**Comment by EminSuleyman** [comment]
> > review is done
> 
> and?
as a conclusion, general structure understood, just need to clarify specific tasks for the backend api, and if frontend is ready I would like to see it too. A question: for what purpose we use taiga api's?

**Comment by paolo-demagistris-polito** [comment]
> as a conclusion, general structure understood, just need to clarify specific tasks for the backend api (1), and if frontend is ready I would like to see it too (2). A question: for what purpose we use taiga api's?(3)

1. Specific functions will be documented starting from this Monday through case studies and narrative use cases. I will seek some help from a research assistant to form, if needed, proper UML use cases
2. Front end is not available. Plan for the so called Minimum Viable Product is to use directly django apps/models through jupyter notebooks in the same python/django environment. This way we don't have to bother with networking and we can sufficiently emulate textual (md part of note book) and coded info (python part)
3. Taiga is the closest "comparable", it has the same planned architecture in terms of FE, API and BE and is aimed at agile project management. By accessing the code a fair understanding of agile pm apps, models and classes can be obtained. Also we should consider a fork of the repo.

**Pull request merged**
